services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mydb
    ports:
      - "5432:5432"

    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10
    

  postgres-init:
    build:
      context: .
      dockerfile: docker/Dockerfile.init
    command: ["/app/postgres-init.sh"]
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mydb
    restart: "no"
    

# volumes:
#   postgres_data:
